### ISSUE TITLE
Отрисовать главного персонажа и его анимации

### ISSUE THREAD

**Issue by D9eka** [D9eka/Antventurer#30]
Список анимаций:
1. Бездействие. _Когда стоит на месте_
2. Передвижение
3. Прыжок + Падение
4. Двойной прыжок
5. Скольжение по стене

[Референс](https://drive.google.com/file/d/1t5Iswhd8QmdNMlFhVa0zch_IvbfHvkHd/view?usp=drive_link)
[Больше референсов](https://itch.io/game-assets/genre-platformer/tag-animation)

Скинуть ссылку на Figma ↓↓↓

**Comment by AlinaBasyrova** [comment]
https://www.figma.com/file/FtCCVvvE7PFN6PUjOVdnEP/%D0%91%D0%B0%D1%81%D1%8B%D1%80%D0%BE%D0%B2%D0%B0-%D0%90.%D0%A0.?type=design&node-id=58%3A19&mode=design&t=Cyfa52YS4BIuoSfD-1 - черновой вариант анимаций, итоговый будет дорабатываться в Dragon Bones
