### ISSUE TITLE
Отрисовать тайлы для локаций "Начало"

### ISSUE THREAD

**Issue by D9eka** [D9eka/Antventurer#31]
[Референсы локаций](https://www.figma.com/file/Gxcm7GFf9tPhG2t4YhYCi2/Untitled?type=design&node-id=466-67&mode=design&t=aEjoleIur0ysjzGm-0)

Референс 1 (текстура тайлов, цветовая гамма)

![Image](https://github.com/D9eka/Antventurer/assets/120364200/60a939fb-48c4-4136-bea9-6132b913d7da)

Референс 2 (форма тайлов, background):

![Image](https://github.com/D9eka/Antventurer/assets/120364200/ab12c83a-fe38-46cd-b61a-69cf3d212760)

Скинуть ссылку на Figma ↓↓↓

**Comment by WatchWitch** [comment]
[https://www.figma.com/file/lxWAerv3XCUzCbzfb1we0O/BG-antventure?type=design&node-id=0%3A1&mode=design&t=bpViv1D61OJlSRCW-1](url)

Будет дорабатываться
