### ISSUE TITLE
Отрисовка итогового варианта UI #1

### ISSUE THREAD

**Issue by D9eka** [D9eka/Antventurer#32]
- Отрисовать экраны: главное меню, загрузка, пауза
- Отрисовать логотип ([вариант](https://www.figma.com/file/FtCCVvvE7PFN6PUjOVdnEP/%D0%91%D0%B0%D1%81%D1%8B%D1%80%D0%BE%D0%B2%D0%B0-%D0%90.%D0%A0.?type=design&node-id=170-189&mode=design&t=dGpzFXHH9kLq51FS-0)), который будет использоваться в экранах загрузки

Скинуть ссылку на Figma ↓↓↓

**Comment by M1chael85** [comment]
https://www.figma.com/file/GRO3oW8rRnoiBxFMQnCt9M/Team-138-%2F-Wireframes-Kit?type=design&node-id=0%3A1&mode=design&t=4mXNChAlYNIrOkLj-1
