### ISSUE TITLE
Подготовить текст для страницы на Яндекс.Игры

### ISSUE THREAD

**Issue by D9eka** [D9eka/Antventurer#36]
Подготовить текст, удовлетворяющий [условиям](https://yandex.ru/dev/games/doc/ru/console/add-new-game#step-fill-in-draft)

Скинуть ссылку на Google-документ ↓↓↓

**Comment by ZVPopovUrfu** [comment]
https://docs.google.com/document/d/1q0sdSMsXwLTPlsIeYUz-QoJV6mt5HHBlEWmCJA-1dCE/edit?usp=sharing
черновик тоже заполнил
