### ISSUE TITLE
Отрисовать тайлы и фон для локации "Кладбище"

### ISSUE THREAD

**Issue by D9eka** [D9eka/Antventurer#40]
## [Референсы](https://www.figma.com/file/Gxcm7GFf9tPhG2t4YhYCi2/Untitled?type=design&node-id=466-67&mode=design&t=MhAe6SwoXOJbKjXC-0)

Когда закончишь, нажми кнопку Close Issue ↘↘↘

**Comment by WatchWitch** [comment]
Моя фигма
https://www.figma.com/file/lxWAerv3XCUzCbzfb1we0O/BG-antventure?type=design&node-id=1%3A2&mode=design&t=91MaiktfRaA7r0cs-1


В общей фигме то же самое
