### ISSUE TITLE
Найти музыку для каждой локации

### ISSUE THREAD

**Issue by D9eka** [D9eka/Antventurer#45]
Найти музыку для локаций: Начало, Кладбище, Зимовальная камера

Сайты для поиска:
- [Indie Game Music](https://indiegamemusic.com/) (только Freeware)
- [cchound](https://www.cchound.com/)
[Больше сайтов](https://www.audiomania.ru/content/muzika-dlya-vashih-proektov-12-tematicheskih-resursov-s-trekami-po-litsenzii-creative-commons/)

Прикрепить архив с музыкой и ссылки на каждый трек

**Comment by ZVPopovUrfu** [comment]
https://drive.google.com/file/d/1vjNa5XSnPM60qtspC-Sy3nOnWYPlHr_A/view?usp=sharing
Ссылка на архив с музыкой. Сюда закинуть не получилось(

https://docs.google.com/document/d/1TUOr3h4vI3I2-Ba2lZzIQiQIH7u-iSn5yZxFTdcStZ0/edit?usp=sharing
Ссылка на информацию о музыке.
