### ISSUE TITLE
Отрисовать след ГГ и смолу

### ISSUE THREAD

**Issue by D9eka** [D9eka/Antventurer#52]
Ширина: 512px
## [Референсы](https://www.figma.com/file/Gxcm7GFf9tPhG2t4YhYCi2/Untitled?type=design&node-id=466-40&mode=design&t=H4Syqnex59TyYjgD-0)

**Comment by AlinaBasyrova** [comment]
Спрайты готовы, по возможности хотелось бы еще сделать анимацию следа гг
