### ISSUE TITLE
Перевести игру на английский язык

### ISSUE THREAD

**Issue by D9eka** [D9eka/Antventurer#58]
Нужно перевести:
- [Интерфейс](https://www.figma.com/file/k9XgBkhpuERGy9LaTrBDcq/General?type=design&node-id=1-3&mode=design&t=wTTsIHUGML9H7cJA-0)
- Диалог с муравьём

Результат: переведённые экраны в Figma и документ с переводом диалогов

**Comment by ZVPopovUrfu** [comment]
https://www.figma.com/file/k9XgBkhpuERGy9LaTrBDcq/General?type=design&node-id=338-1748&mode=design&t=mRtJHSpdX5VUr6w1-4

https://docs.google.com/document/d/1Nit5szhSOQ3uE01emy3mt6KzZ5uqnRgpHClvcYFQDLg/edit?usp=sharing
