### ISSUE TITLE
Написать текст концовки

### ISSUE THREAD

**Issue by D9eka** [D9eka/Antventurer#75]
Написать текст концовки на [экране](https://www.figma.com/file/k9XgBkhpuERGy9LaTrBDcq/General?type=design&node-id=56-1903&mode=design&t=aOqrP5VC6cCrYKZk-0)

**Comment by ZVPopovUrfu** [comment]
Написал в разделе "Динамика развития игры" и добавил на главную доску в фигме там где у нас UI
